apiVersion: apps/v1
kind: Deployment
namespace: app_region
metadata:
  name: redis-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      name: my-redis
  template:
    metadata:
      labels:
        name: my-redis
    spec:
      containers:
      - name: redis-container
        image: redis
        ports:
        - containerPort: 80
