apiVersion: v1
kind: Service
namespace: app_region
metadata:
  name: app-lb
spec:
  type: LoadBalancer
  selector:
    name: my-app
  ports:
    - port: 80
      targetPort: 8000
      nodePort: 31000
